[package]
name = "nexa-desktop"
version = "0.6.0"
description = "Nexa Desktop"
authors = ["Nexa contributors"]
edition = "2021"

[lib]
name = "nexa_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-opener = "2"
tauri-plugin-shell = "2"
tauri-plugin-single-instance = "2"
